export const screenName = {
    SignIn: "SignIn",
    SignUp: "SignUp",
    Home: "Home",
    BottomTab: "BottomTab",
    Test: "Test",
    WaitingRoom: "WaitingRoom",
    ManageQuiz: "ManageQuiz",
    CreateQuiz: "CreateQuiz",
    EditQuiz: "EditQuiz",
    ListQuestion: "ListQuestion",
    ManageQuestion: "ManageQuestion",
    PlayQuiz: "PlayQuiz",
    MultipleChoice: "MultipleChoice",
    CheckBox: "CheckBox",
    FillInTheBlank: "FillInTheBlank",
    DragAndSort: "DragAndSort",
    AnswerMultiChoice: "AnswerMultiChoice",
    AnswerCheckBox: "AnswerCheckBox",
    HostScreen: "HostScreen",
    Overview: "Overview",
    Questions: "Questions"
}